### ISSUE TITLE
Options on representing address extension for street address

### ISSUE THREAD

**Issue by aschuler84** [HL7Austria/hl7-at-fhir-profiles#1]
As part of the AustrianPatient base profile, we need to add an extension on the address to represent a street address not only by its line but separated in `streetName`, `streetNumber`, `floor-` and  `doorNumber`. Therefore 3 possible variants available, each with pros and cons. I'd like to start a discussion on the benefits of choosing one option over the other. When we come to a conclusion, respective option will be used to represent the exploded street address.

- Option 1: add an extension on the `Patient.address` element in the `AustrianPatientProfile`
   - PROS: easy, no additional extensions needed
   - CONS: address extension is only applicable in context of the AustrianPatient and no other possible Resource that contains an `Address`-element
- Option 2: extend the element `address.line`
   - PROS: this is basically done in the German base-profile and it allows for reuse
- Option 3: Extension auf Level Address Complex Type
   - PROS: this is what is done in the Dutch base-profile, also allows for reuse

**Comment by oliver-krauss** [comment]
Additional discussion point: The name AustrianAddress suggests that this is an Address in the Austrian Postal System, which I assumed while designing this. 

From feedback of @regelkraut and @aschuler84 apparently this just means -> How an address is represented in Austrian *-ehealth-systems, and this can be ANY country. 
We need renaming (and documentation) clarifying this. 

Suggestion for discussion:
AustrianRepresentationOfAddress

**Comment by oliver-krauss** [comment]
Added Impl for AustrianRepresentationOfAddress, and clarified discussion. Validitiy of changes pending discussion and #12

**Comment by oliver-krauss** [comment]
FYI -> https://simplifier.net/BasisprofilDE/address-de-basis-0.2/~details

**Comment by oliver-krauss** [comment]
Opposing ISO -> ISO 21090. Also already has extensions for HouseNumber, Street, ...

**Comment by regelkraut** [comment]
correct, there already are a lot of extensions for ISO 21090 based address attributes
full list can be found here for STU3: [http://www.hl7.org/fhir/stu3/datatypes-extras.html#Address](http://www.hl7.org/fhir/stu3/datatypes-extras.html#Address)
we should use those where possible

additional info to the three options - HL7 CH is also using option 2 for their profiles like HL7 DE

**Comment by aschuler84** [comment]
I have the same opinion as @regelkraut  on using the existing ISO 21090 extensions, also this makes my question above irrelevant.

**Comment by aschuler84** [comment]
I updated the current Austrian address to make use of the ISO 21090 profiles, however there is still a problem with door and floor elements. There is no designated profile for either of the two needed elements. The only profile that allows, according to ISO21090 to specify that information is through using the unitType or unitId profile. However this would lead us to having 2 Elements with the same profile, which we then are no longer to distinguish (at least not based on the profile) from each other. 

There are several options on how to deal with these two elements. Nonetheless, I will describe the options #8

**Comment by regelkraut** [comment]
The discussion concerning the elements for floor & door was resolved, see decision in issue #8, the profile for address can now be finalized.

**Comment by regelkraut** [comment]
Commit was successfully applied with issue #8 , issue will be closed.
