### ISSUE TITLE
Conventions

### ISSUE THREAD

**Issue by oliver-krauss** [HL7Austria/hl7-at-fhir-profiles#12]
from the discussion in #1 -> We need naming conventions for the following:
- Profiles
- Extensions
- fieldnames
- valuesetnames

In addition we must define a convention of how to work with this repository / profiling in general:
- How to work with GIT (merge vs. rebase)
- How to use the labels / enable the process of submitting change requests
- How to submit proposals for new * (Profiles....)
- How to resolve the discussion points and how to document them (see gForge Tracker)

**Comment by oliver-krauss** [comment]
TO everyone. Please add suggestions for additional conventions we need.

**Comment by oliver-krauss** [comment]
NOTE resolving discussion of how to resolve discussion in #13

**Comment by oliver-krauss** [comment]
naming conventions will be discussed in #14

**Comment by oliver-krauss** [comment]
So Reinhard will probably upload the doc-pdf but here the short summary:
- Rebase because the project will stay small
- labels (discussion, review, hot, enhancement, bug, blocked)
- proposals have the label enhancement

**Comment by oliver-krauss** [comment]
Motion stattgefunden - Krauss / Schuler - 5 für, 0 enthalten, 0 gegen

**Comment by oliver-krauss** [comment]
@regelkraut will wait till protocol & readme update for closing this

**Comment by oliver-krauss** [comment]
@regelkraut Only the Explanation of your created templates is missing. Please create, then add discussion label for next Call

**Comment by regelkraut** [comment]
Here is the documentation of the decision we made in our TC FHIR call on January 28th 2019 concerning decision& ballot comments on issues:

decision comments in github issues:
----------------------------
**Motion:**
Exact wording of the motion which will be moved.

**Change Type:**
describes the severtiy of the proposed change -> HL7 International categories (Any, None, Non-substantive, Compatible-substantive, Non-compatible)

**(Ballot) Resolution:**
 final resolution -> HL7 International (ballot) categories (Persuasive, Persuasive with Mod, ...)

**Mover/Seconder: For-Against-Abstain:**


Ballot (if applicable) comments in github issues:
--------------------------
**Ballot Info:** 
 from which ballot it came from

**Ballot Weight:** 
 categories (and codes) from HL7 Austria ballots for a comment
 -> NEG-S (negative, serious), NEG-G (negative, minor), 
    Z-V (approval with proposal), Z-T (approval - typo), Z-F (approval with question), Z-K (approval with comment)

--------------------------

**Motion:**
To use the issue templates which were created [here](https://github.com/HL7Austria/hl7-at-fhir-profiles/tree/master/.github/ISSUE_TEMPLATE) and the comments as decribed in this comment.

**Change Type:**
Compatible-substantive

**(Ballot) Resolution:**
Persuasive

**Mover/Seconder: For-Against-Abstain:**
Oliver Krauss/Stefan Sabutsch: 8-0-0

I will add these with further explantion in our `contributing.md` file once issue #12 is resolved.
The templates were already created and will be documented in `contributing.md` as well.

**Comment by oliver-krauss** [comment]
As the related branch was rebased yesterday, this issue is finished
