### ISSUE TITLE
Create Issue Template according to G-Forge Tracker

### ISSUE THREAD

**Issue by oliver-krauss** [HL7Austria/hl7-at-fhir-profiles#13]
See -> https://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=2839&start=0 for example.

Create a git-template for our issues according to gForge. This ensures compliance with HL7 FHIR Guidelines, and leverages a time tested process.

**Comment by regelkraut** [comment]
I will create a "custom-template" based on the github mechanisms:
[https://help.github.com/articles/creating-issue-templates-for-your-repository/](url)

**Comment by regelkraut** [comment]
Templates for "Feature Requests" and "Bug Reports" with the parameters as discussed during the TC FHIR call from November 27th created.
Review will be done in the call on December 17th.

**Comment by aschuler84** [comment]
Motion Schuler/Helm 11-0-0: Passt so
