### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by oliver-krauss** [HL7Austria/hl7-at-fhir-profiles#14]
from #13 submit a proposal for the naming conventions

**Comment by oliver-krauss** [comment]
Ok so here goes:

**Profile**
ProfileName = Use, ParentProfile
Use = Whatever. 
Ex. AustrianPatient Use = Austria; ParentProfile = Patient

**Extension**
ExtensionName = [ProfileItIsFor], {FieldWithChildrenItIsIn}, FieldItAdds
ProfileItIsFor = Either Base Profile or Profile previously defined (optional if extension can be anywhere -> Ex. NullFlavor)
FieldWithChildrenItIsIn = Optional and Repeating, may have clarification if  (ex. Composition.SectionPatient.SubsectionAllergies -> CompositionSectionPatientSubsectionAllergies)
FieldItAdds = unique naming for field
Ex. AustrianAddressStreet

**Comment by oliver-krauss** [comment]
As HL7 FHIR has pretty precise definitions of fields (camelCase, starts lowercase, should be clear what is meant, even without reading the description) I don't think we need specific naming conventions for fieldnames.

**Comment by oliver-krauss** [comment]
Ok this time I am prepared. Come at me @regelkraut

**Comment by oliver-krauss** [comment]
addendum: If Use == realm -> lowercase country code with "-" is allowed ex. "at-"

**Comment by OliverKrauss** [comment]
ok I finally did't forget to do this before a call. I will do this in a pull request as we once upon decided that changes should be done.

**Comment by regelkraut** [comment]
*Motion during TC FHIR Call on April 29th 2019:*
We will accept the naming convention as described in this issue.

*Change Type:*
Compatible-substantive

*(Ballot) Resolution:*
Persuasive with Mod

*Mover/Seconder: For-Against-Abstain:*
Andreas Schuler/Oliver Krauss: 4-0-0

**Comment by regelkraut** [comment]
pull request was merged into master during the TC FHIR Call on April 29th 2019, this issue will therefore be closed
