### ISSUE TITLE
Define slice & discriminator for identifiers

### ISSUE THREAD

**Issue by regelkraut** [HL7Austria/hl7-at-fhir-profiles#17]
According to the result of the requirements evaluation we need identifiers in the profile for:

- SVNr (social security number)

- bPK-GH (Austrian specific person identifier for healthcare)

- local patient ids

optional:
- EKVK (EHIC identifier)

- NGID (new born id)

ToDos:

- The definition of slice and a discriminator needs to be done.

- Clarification which attributes of a [identifier](http://build.fhir.org/datatypes.html#Identifier) are we using
- decisions from previous calls - OIDs are used in system as namespace, the according url will be provided as additional information (as part of the assigner?)

- Creation of the slices for the above mentioned identifiers

**Comment by regelkraut** [comment]
result from call on July 31st:
Slice:

- discriminator proposal: system

- Ordering relevant (is ordered)? -> no

- slice open or closed or open at end -> open

SVNR – socialSecuriyNumber, 0..1

- system = OID

- value = the actual SVNr
- assigner.reference = Link of the Austrian OID Portal
- assigner.display = "OID Portal Österreich"
- use: tbd
- type: tbd
- period: tbd

bPK-GH, 0..1
- system = OID
- value = the actual bpkgh
- assigner.reference = Link of the Austrian OID Portal
- assigner.display = "OID Portal Österreich"
- use: tbd
- type: tbd
- period: tbd

**Comment by oliver-krauss** [comment]
Motion -> For discriminator of the identifiers we use "type.coding.code" as this allows us to identify the "local patient id(s)". This allows us to identify all required ids, altough it may prove difficult for the optional EKVK and NGID. 
EKVK and NGID will be handled in separate issues.

Motion by: Oliver Krauss
Seconded: Andreas Schuler
For, Against, Abstain: 6 / 0 / 0

**Comment by oliver-krauss** [comment]
Attribute "Patient.identifier.use" will not be defined by the profile
Attribute "Patient.identifier.period" will not be defined by the profile

**Comment by oliver-krauss** [comment]
Local Patient ID – localPatientId, 0..1
    system = OID
    value = the actual local id
    assigner.reference = undefined
    assigner.display = undefined
    type: PI

**Comment by oliver-krauss** [comment]
Motion for the two comments above:
Motion by: Oliver Krauss
Seconded: Andreas Schuler
For, Against, Abstain: 6 / 0 / 0

**Comment by regelkraut** [comment]
final layout for the identifier slices (descriminator=type):

SVNr – socialSecurityNumber, 0..1
- use: no definition
- value = the actual SVNr
- system = OID "urn:oid:1.2.40.0.10.1.4.3.1"
- assigner.reference = Link to the Austrian OID Portal
- assigner.display = "Hauptverband der österreichischen Sozialversicherungsträger"
- type: "SS"
- period: no definition

bPK-GH - bPK, 0..*
- use: no definition
- value = the actual bPK, e.g. "GH:1234..."
- system = OID "urn:oid:1.2.40.0.10.2.1.1.149"
- assigner.reference = Link to the Austrian OID Portal
- assigner.display = "Bundesministerium für Inneres"
- type: "NI"
- period: no definition

local patient id - localPatientId, 0..1
- use: no definition
- value = the actual local PID
- system = OID of the sender
- assigner.reference = Link to the Austrian OID Portal where the OID of the sender is located
- assigner.display = display name of the sender
- type: "PI"
- period: no definition

necessary committs are already applied, new issue for EKVK & NGID created (#18) this issue will therefore be closed.
