### ISSUE TITLE
Elementname for representing floor- and door-number 

### ISSUE THREAD

**Issue by aschuler84** [HL7Austria/hl7-at-fhir-profiles#2]
Acc. to existing representations of a patients in Austria (ELGA, ZP-I, etc.) a patient has a single element to represent both floor- and door-number.

We now could follow this approach an define the element in the AustrianPatient like `address.floorDoorNumber` or alternatively we could separate these values in `address.floorNumber` and `address.doorNumber`.

**Comment by oliver-krauss** [comment]
Did an initial version of this being split. discussion to follow in FHIR TC

**Comment by aschuler84** [comment]
So we already talked about the field being separated in two distinct elements, however as it turns out, event the ISO21090 only defines one type for things like floor/apartment etc. Thus as we now rely on the ISO21090 based FHIR profiles for address representation, we should bring these two bits of information together again and use the profile UnitType to represent it in the AustrianAddress 

See other solution options in #8

**Comment by aschuler84** [comment]
Motion Schuler/Fürst 11-0-0 to close #2 -> Discussion will be resolved in #8
