### ISSUE TITLE
OID - Datatype

### ISSUE THREAD

**Issue by oliver-krauss** [HL7Austria/hl7-at-fhir-profiles#22]
**Real Submitter**
Oliver Krauss

**Resource(s)/Profiles incl. Version**
at-Patient

**Links**
http://hl7.org/fhir/STU3/datatypes.html#oid
https://github.com/HL7Austria/hl7-at-fhir-profiles/blob/master/AustrianPatient/AustrianPatient.xml 

**Priority**
Major?

**Describe the bug**
In several fields for the austrian Patient we use OID. Especially in the identifier. We defined this as String currently, while there is an oid datatype available.

**To Reproduce**
Look at the Resource and see.

**Expected behavior**
Switch all fields that SHALL be oid to the datatype oid.

**Attachments**
-

**Additional context**
-

**Comment by aschuler84** [comment]
Motion Sabutsch/Mense: 10-0-0 Change type to OID.
TBD @oliver-krauss

**Comment by oliver-krauss** [comment]
Ok. So I was stupid. Turns out we never defined OID anywhere. We USE OIDs to define our system values, but that has no relation to us actually restriting to OID there, as the identifiers (SVNR, BPK-GH and LocalPatientID) are not an OID

**Comment by oliver-krauss** [comment]
Thus I actually request closing this issue with the invalid label.

**Comment by regelkraut** [comment]
This change is actually not necessary, see also comment from @oliver-krauss  on March 22nd 2019:

**Motion during TC FHIR Call on April 29th 2019:**
Revert the motion from March 21st.

**Change Type:**
Compatible-substantive

**(Ballot) Resolution:**
Persuasive

**Mover/Seconder: For-Against-Abstain:**
Oliver Krauss/Andreas Schuler: 5-0-0

**Comment by regelkraut** [comment]
Ticket can be closed
