### ISSUE TITLE
Research possible extension for element AustrianPatient.citizenship

### ISSUE THREAD

**Issue by aschuler84** [HL7Austria/hl7-at-fhir-profiles#3]

**Comment by oliver-krauss** [comment]
I suggest this one: https://www.hl7.org/fhir/extension-patient-citizenship.html

**Comment by regelkraut** [comment]
concerning the necessary valueSets - ELGA is using specific values for country codes (ISO 3166-1 alpha 3 2016) in the CDA guidelines
During the TC FHIR call on July 2nd we were asked to add them to our profile.
Link to the "ELGA_Ländercodes":
[https://termpub.gesundheit.gv.at/TermBrowser/gui/main/main.zul?loadType=ValueSet&loadName=ELGA_Laendercodes](url)

**Comment by aschuler84** [comment]
It should be possible by adding another binding to the available ValueSets. Though this would involve altering the existing HL7 citizenship extension. 
Possible approaches involve: 
A) use citizenship extension and build an "AustrianCitizenship" extension that is derived from the HL7 citizenship extension
B) build an extension "AustrianCitizenship" that has no relation with the HL7 Citizenship Extension, however use exiting extension as a blueprint

**Comment by aschuler84** [comment]
Input from Stefan Sabutsch in last tc-meeting to make use of the terminologies and value sets already defined in ELGA: https://termpub.gesundheit.gv.at:443/TermBrowser/gui/main/main.z ul?loadType=ValueSet&loadName=ELGA_Laendercodes

**Comment by aschuler84** [comment]
TBD @aschuler84: Finish this!

**Comment by regelkraut** [comment]
Discussed on TC FHIR Call September 10th:
we will use the official HL7 extension with a binding to the ELGA value set for country codes based on ISO 3166-1, see also https://termpub.gesundheit.gv.at/TermBrowser/gui/main/main.zul?loadType=ValueSet&loadName=ELGA_Laendercodes

**Comment by regelkraut** [comment]
Commit was successfully applied, issue will be closed.
