### ISSUE TITLE
Define an extension for address.doorFloorNumber

### ISSUE THREAD

**Issue by aschuler84** [HL7Austria/hl7-at-fhir-profiles#8]
depends on #2 
address.doorFloorNumber is part of an AustrianAdress type and represents the number of either floor or door at a specific address.

**Comment by oliver-krauss** [comment]
Sorry ignore that comment. Just saw that the discussion there is  actually in #1

**Comment by oliver-krauss** [comment]
See #2, added this as two separate extensions

**Comment by aschuler84** [comment]
Options on representing door and floor number (fyi: Option 1 is already described in #2)

Option 2: Remove both elements floor and door from the address and use `additonalLocator` (as described in ISO21090) to represent information about door, floor, apartment 

Option 3: Use our own primarily defined extension and change them to be used in context of `address.line`

For the sake of completeness find the descriptions from ISO 21090 below.
   |   |  
 -- | -- | --
additionalLocator  | additional locator | This can be a unit designator, such as apartment number, suite number, or floor. There may be several unit designators in an address (e.g., "3rd floor, Appt. 342"). This can also be a designator pointing away from the location, rather than specifying a smaller location within some larger one (e.g., Dutch "t.o." means "opposite to" for house boats located across the street facing houses)
unitId | unit identifier | The number or name of a specific unit contained within a building or complex, as assigned by that building or complex
unitType | unit designator | Indicates the type of specific unit contained within a building or complex. E.g. Apartment, Floor

**Comment by MEmbacher** [comment]
Is there any possibility to build a connection between unitID und unitType?
I guess not. So with the ISO 21090 profiles we will be able to represent only one of the information at the same time.

I personally tend to option 2. In practice it is difficult to implement a reasonable solution for the input of the information about door and floor number without overly restricting the permissible input options.
E.g. strict numeric input, which seperators are allowed ...

So in case of additionalLocator it is clear that this is just a additional information without any restriction on the data content itself.

**Comment by regelkraut** [comment]
Aus TC FHIR Call vom 11.10.2019
**Motion:** Umsetzung von Option 2
**Change Type:** Compatible-substantive
**Resolution:** final resolution: Persuasive with Mod
**Mover/Seconder: For-Against-Abstain:** Schuler/Asenbaum: 5-0-0

**Comment by regelkraut** [comment]
Commit was successfully applied, issue will be closed.
